package org.sample;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.8.redhat-7
 * 2015-07-08T12:42:09.321-05:00
 * Generated source version: 2.6.8.redhat-7
 * 
 */
@WebServiceClient(name = "SalaryIncrement", 
                  wsdlLocation = "file:/home/rick/workspace/FSW/6GA3/MultipleSSLRef/FSW_SalaryUpdate/src/main/resources/wsdl/SalaryIncrement.wsdl",
                  targetNamespace = "http://sample.org/SalaryIncrement/") 
public class SalaryIncrement extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sample.org/SalaryIncrement/", "SalaryIncrement");
    public final static QName SalaryIncrementPort = new QName("http://sample.org/SalaryIncrement/", "SalaryIncrementPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/rick/workspace/FSW/6GA3/MultipleSSLRef/FSW_SalaryUpdate/src/main/resources/wsdl/SalaryIncrement.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SalaryIncrement.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/rick/workspace/FSW/6GA3/MultipleSSLRef/FSW_SalaryUpdate/src/main/resources/wsdl/SalaryIncrement.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SalaryIncrement(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SalaryIncrement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalaryIncrement() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SalaryIncrement(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SalaryIncrement(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SalaryIncrement(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SalaryIncrementPortType
     */
    @WebEndpoint(name = "SalaryIncrementPort")
    public SalaryIncrementPortType getSalaryIncrementPort() {
        return super.getPort(SalaryIncrementPort, SalaryIncrementPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalaryIncrementPortType
     */
    @WebEndpoint(name = "SalaryIncrementPort")
    public SalaryIncrementPortType getSalaryIncrementPort(WebServiceFeature... features) {
        return super.getPort(SalaryIncrementPort, SalaryIncrementPortType.class, features);
    }

}
