package org.sample;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8.redhat-7
 * 2015-07-08T12:42:09.292-05:00
 * Generated source version: 2.6.8.redhat-7
 * 
 */
@WebService(targetNamespace = "http://sample.org/SalaryIncrement/", name = "SalaryIncrementPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SalaryIncrementPortType {

    @WebResult(name = "updatedsalary", targetNamespace = "")
    @RequestWrapper(localName = "IncrementSalary", targetNamespace = "http://sample.org/SalaryIncrement/", className = "org.sample.IncrementSalary")
    @WebMethod(operationName = "IncrementSalary", action = "http://sample.org/SalaryIncrement/IncrementSalary")
    @ResponseWrapper(localName = "IncrementSalaryResponse", targetNamespace = "http://sample.org/SalaryIncrement/", className = "org.sample.IncrementSalaryResponse")
    public int incrementSalary(
        @WebParam(name = "insalary", targetNamespace = "")
        int insalary
    );
}
