package org.namecleaning;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8.redhat-7
 * 2015-07-08T08:08:39.068-05:00
 * Generated source version: 2.6.8.redhat-7
 * 
 */
@WebService(targetNamespace = "http://www.text.standardization/NameCleanup/", name = "NameCleanupPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface NameCleanupPortType {

    @WebResult(name = "cleanedName", targetNamespace = "")
    @RequestWrapper(localName = "NameCleanup", targetNamespace = "http://www.text.standardization/NameCleanup/", className = "org.namecleaning.NameCleanup")
    @WebMethod(operationName = "NameCleanup", action = "http://www.text.standardization/NameCleanup/NameCleanup")
    @ResponseWrapper(localName = "NameCleanupResponse", targetNamespace = "http://www.text.standardization/NameCleanup/", className = "org.namecleaning.NameCleanupResponse")
    public java.lang.String nameCleanup(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
