package org.namecleaning;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.8.redhat-7
 * 2015-07-08T08:08:39.095-05:00
 * Generated source version: 2.6.8.redhat-7
 * 
 */
@WebServiceClient(name = "NameCleanup", 
                  wsdlLocation = "file:/home/rick/workspace/FSW/6GA3/MultipleSSLRef/FSW_SalaryUpdate/src/main/resources/wsdl/NameCleanup.wsdl",
                  targetNamespace = "http://www.text.standardization/NameCleanup/") 
public class NameCleanup_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.text.standardization/NameCleanup/", "NameCleanup");
    public final static QName NameCleanupPort = new QName("http://www.text.standardization/NameCleanup/", "NameCleanupPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/rick/workspace/FSW/6GA3/MultipleSSLRef/FSW_SalaryUpdate/src/main/resources/wsdl/NameCleanup.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NameCleanup_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/rick/workspace/FSW/6GA3/MultipleSSLRef/FSW_SalaryUpdate/src/main/resources/wsdl/NameCleanup.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NameCleanup_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NameCleanup_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NameCleanup_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NameCleanup_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NameCleanup_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NameCleanup_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns NameCleanupPortType
     */
    @WebEndpoint(name = "NameCleanupPort")
    public NameCleanupPortType getNameCleanupPort() {
        return super.getPort(NameCleanupPort, NameCleanupPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NameCleanupPortType
     */
    @WebEndpoint(name = "NameCleanupPort")
    public NameCleanupPortType getNameCleanupPort(WebServiceFeature... features) {
        return super.getPort(NameCleanupPort, NameCleanupPortType.class, features);
    }

}
