
package org.example.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * Fri Sep 25 11:18:36 CDT 2015
 * Generated source version: 2.7.11.redhat-3
 */

@XmlRootElement(name = "getOneResponse", namespace = "http://example.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOneResponse", namespace = "http://example.org/")

public class GetOneResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

