
package org.example.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * Fri Sep 25 11:18:36 CDT 2015
 * Generated source version: 2.7.11.redhat-3
 */

@XmlRootElement(name = "getOne", namespace = "http://example.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOne", namespace = "http://example.org/")

public class GetOne {


}

